/**
 * The Caddy module: generated by the pinned xcaddy, committed, and compared on every PR.
 *
 * ★ WHY GENERATE-AND-COMMIT, NOT `xcaddy build` AT RELEASE. xcaddy resolves the dependency
 *   graph in a temporary module and throws its go.sum away, so a release built that way could
 *   not say which of its ~170 modules it contained until after the fact. nixpkgs solves the
 *   same problem the same way (`XCADDY_SKIP_BUILD=1 xcaddy build …`, then vendors the result).
 *   Here the generated go.mod, go.sum and main.go are COMMITTED: every module version is in a
 *   reviewed diff, and the release builds them with `-mod=readonly`, which refuses any
 *   module whose content does not match go.sum.
 * ⛔ THE COMMITTED FILES MUST BE EXACTLY WHAT THE PINNED xcaddy WRITES. `compareCaddyModule`
 *   regenerates into a scratch directory and diffs all three; CI fails on any difference, so
 *   a hand-edited go.mod — or a plugin bumped in build.ts but not regenerated — cannot ship.
 */
import { mkdir, mkdtemp, readdir, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import type { XcaddyBuild } from '../../builds/types.ts';
import { type Go, goEnv } from './go.ts';
import { requireDigest, run } from './run.ts';

/** The files xcaddy writes that this repository commits. */
export const MODULE_FILES = ['go.mod', 'go.sum', 'main.go'] as const;

/** `xcaddy build` arguments for a build, in the manifest's `--with` order. */
export const xcaddyArgs = (build: XcaddyBuild): string[] => [
  'build',
  build.caddy.version,
  ...build.plugins.flatMap((plugin) => ['--with', `${plugin.module}@${plugin.version}`]),
];

/** Run the pinned xcaddy; return the directory holding the module it generated. */
export const generateCaddyModule = async (go: Go, build: XcaddyBuild, work: string) => {
  const gobin = join(work, 'bin');
  await mkdir(gobin, { recursive: true });
  // ★ `go install module@version` is checked against sum.golang.org, like any module.
  await run([go.bin, 'install', `${build.xcaddy.module}@${build.xcaddy.version}`], {
    env: goEnv(go, { GOBIN: gobin }),
  });
  const scratch = join(work, 'xcaddy');
  await mkdir(scratch, { recursive: true });
  await run([join(gobin, 'xcaddy'), ...xcaddyArgs(build)], {
    cwd: scratch,
    // ★ SKIP_BUILD: generate and resolve only. SKIP_CLEANUP: keep the buildenv to read.
    //   TMPDIR: where xcaddy puts `buildenv_<timestamp>` (the nixpkgs recipe does the same).
    env: goEnv(go, { TMPDIR: scratch, XCADDY_SKIP_BUILD: '1', XCADDY_SKIP_CLEANUP: '1' }),
  });
  const envs = (await readdir(scratch)).filter((name) => name.startsWith('buildenv_'));
  if (envs.length !== 1) throw new Error(`expected one xcaddy buildenv, found: ${envs.join(', ')}`);
  return join(scratch, envs[0] ?? '');
};

/** Differences between the committed module and a fresh generation; empty when identical. */
export const compareCaddyModule = async (go: Go, build: XcaddyBuild, root: string) => {
  const work = await mkdtemp(join(tmpdir(), 'caddy-module-'));
  try {
    const generated = await generateCaddyModule(go, build, work);
    const problems: string[] = [];
    for (const file of MODULE_FILES) {
      const committed = Bun.file(join(root, build.moduleDir, file));
      const fresh = await Bun.file(join(generated, file)).text();
      if (!(await committed.exists())) problems.push(`${build.moduleDir}/${file} is missing`);
      else if ((await committed.text()) !== fresh) {
        problems.push(`${build.moduleDir}/${file} differs from what xcaddy generates`);
        await run(['diff', '-u', join(root, build.moduleDir, file), join(generated, file)], {
          echo: false,
        }).catch((error: unknown) => console.log(String(error)));
      }
    }
    return problems;
  } finally {
    await rm(work, { force: true, recursive: true });
  }
};

/** Write a fresh generation over the committed module (`bun run caddy:regenerate`). */
export const writeCaddyModule = async (go: Go, build: XcaddyBuild, root: string) => {
  const work = await mkdtemp(join(tmpdir(), 'caddy-module-'));
  try {
    const generated = await generateCaddyModule(go, build, work);
    for (const file of MODULE_FILES) {
      await Bun.write(join(root, build.moduleDir, file), Bun.file(join(generated, file)));
    }
  } finally {
    await rm(work, { force: true, recursive: true });
  }
};

/**
 * Caddy's LICENSE, from the module cache: the copy go.sum verified. ⛔ Refused unless it is
 * the digest pinned in build.ts, so the licence text shipped is a reviewed one.
 */
export const caddyLicense = async (go: Go, build: XcaddyBuild, root: string): Promise<string> => {
  const { stdout } = await run([go.bin, 'mod', 'download', '-json', build.caddy.module], {
    cwd: join(root, build.moduleDir),
    env: goEnv(go),
  });
  const info = JSON.parse(stdout) as { Dir?: string; Version?: string };
  if (info.Dir === undefined || info.Version !== build.caddy.version) {
    throw new Error(`go mod download ${build.caddy.module}: unexpected ${stdout}`);
  }
  const path = join(info.Dir, 'LICENSE');
  await requireDigest(path, build.licenseSha256, 'caddy LICENSE');
  return path;
};
