/**
 * What a build here IS, as a type: every input a release records, and nothing that is not one.
 *
 * ⛔ A BUILD IS ITS INPUTS, WRITTEN DOWN. Each field below is either a pinned upstream fact
 *   (a version, a commit, a digest) or a build flag. The release notes, the tag, the asset
 *   names and the smoke test are all computed from these values — never typed twice — so a
 *   release cannot say it was built from something it was not.
 * ★ `revision` IS OURS, NOT THE VENDOR'S. It counts rebuilds of the same upstream version (a
 *   new Go patch, a changed flag). Releases are immutable here, so a rebuilt `2.11.4` is
 *   `-r2`, never a replaced `-r1`.
 */

/** The one platform this repository builds for. ★ Nothing else here lacks a vendor binary. */
export const TARGET = { goarch: 'arm64', goos: 'darwin', platform: 'darwin-arm64' } as const;

/** A Go module at an exact version, `v`-prefixed as `go.mod` writes it. */
export type ModulePin = { readonly module: string; readonly version: string };

/** Flags every build passes to `go build`. */
export type GoFlags = {
  /** `-ldflags`, one flag per entry. */
  readonly ldflags: readonly string[];
  /** `-tags`, joined with commas. Empty for none. */
  readonly tags: readonly string[];
  /**
   * `-buildvcs`. ★ Off for a module generated in this repository (the binary would record
   *   THIS repository's commit, so every merge would change its bytes); on for an upstream
   *   clone, where it records the upstream commit — which is exactly what an auditor wants.
   */
  readonly buildvcs: boolean;
};

type BuildBase = {
  /** Release and asset name prefix; also the installed binary's name. */
  readonly name: string;
  /** The upstream version, without a `v`. */
  readonly version: string;
  /** Rebuild counter for this upstream version, from 1. */
  readonly revision: number;
  /**
   * The upstream source's own commit time (ISO-8601, UTC). ★ Every archive entry carries it
   *   as its mtime, so an archive depends on its inputs and not on the clock of the build.
   */
  readonly sourceDate: string;
  /** SHA-256 of the upstream LICENSE shipped inside the archive, measured when pinned. */
  readonly licenseSha256: string;
  /** SPDX id of that licence, for the release notes. */
  readonly license: string;
  readonly flags: GoFlags;
  /** What the smoke test runs, on the built binary, before anything is packed. */
  readonly smoke: {
    /** Arguments of one command that must exit 0 … */
    readonly args: readonly string[];
    /** … and whose stdout must contain each of these. */
    readonly expect: readonly string[];
  };
};

/**
 * A Caddy with plugins, generated by xcaddy into a module committed in this repository.
 * ★ The module is generated ONCE by `bun run caddy:regenerate` and COMMITTED (go.mod, go.sum,
 *   main.go), so every dependency version is reviewable in a diff. CI regenerates it with the
 *   same pinned xcaddy and fails on any difference (scripts/verify.ts).
 */
export type XcaddyBuild = BuildBase & {
  readonly kind: 'xcaddy';
  /** Directory holding the committed module, relative to the repository root. */
  readonly moduleDir: string;
  readonly caddy: ModulePin;
  readonly xcaddy: ModulePin;
  /** In `--with` order, which is the order xcaddy writes the imports in. */
  readonly plugins: readonly ModulePin[];
  /** `caddy list-modules --versions --skip-standard`, one line each, sorted. A file path. */
  readonly modulesFile: string;
};

/** A Go program built from a clone of its upstream repository at a pinned commit. */
export type GitBuild = BuildBase & {
  readonly kind: 'git';
  /** `https://github.com/<owner>/<repo>.git` */
  readonly repository: string;
  /** The upstream tag the clone checks out … */
  readonly tag: string;
  /** … which must resolve to exactly this commit, or the build refuses. */
  readonly commit: string;
  /** SHA-256 of the upstream go.mod and go.sum at that commit. */
  readonly goModSha256: string;
  readonly goSumSha256: string;
  /** The package `go build` builds, relative to the clone. */
  readonly package: string;
};

export type Build = XcaddyBuild | GitBuild;
